# -*- coding: utf-8 -*-
"""Tugas_Dashboard_DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQHoEUVkNQodDe37dmDFzLkAiFrRmASb
"""

import pandas as pd
import plotly.express as px
import dash
from dash import dcc, html
from dash.dependencies import Input, Output

# Data preprocessing
# Pastikan file datasets.xlsx berada di direktori yang sama dengan script ini
data = pd.read_excel("datasets.xlsx", sheet_name="Worksheet")

# Filter hanya data "Diperiksa" dan "Melanggar"
filtered_data = data[data['status_pemeriksaan'].isin(['Diperiksa', 'Melanggar'])]

# Create the Dash app
app = dash.Dash(__name__)

# App layout
app.layout = html.Div([
    # Basic Elements
    html.H1("Dashboard Pemeriksaan Kendaraan BPTD"),
    html.P("Visualisasi jumlah kendaraan diperiksa dan melanggar berdasarkan wilayah BPTD."),

    # Widgets
    dcc.Dropdown(
        id='year-dropdown',
        options=[{'label': year, 'value': year} for year in filtered_data['tahun'].unique()],
        value=filtered_data['tahun'].min(),
        placeholder="Pilih Tahun"
    ),
    dcc.Slider(
        id='threshold-slider',
        min=filtered_data['jumlah'].min(),
        max=filtered_data['jumlah'].max(),
        value=filtered_data['jumlah'].min(),
        marks={int(i): str(int(i)) for i in range(int(filtered_data['jumlah'].min()), int(filtered_data['jumlah'].max()), 1000)},
        tooltip={"placement": "bottom", "always_visible": True},
    ),

    # Chart
    dcc.Graph(id='bar-chart'),
])

# Callback to update the chart
@app.callback(
    Output('bar-chart', 'figure'),
    [Input('year-dropdown', 'value'), Input('threshold-slider', 'value')]
)
def update_chart(selected_year, threshold_value):
    # Filter data based on selected year and threshold
    filtered = filtered_data[(filtered_data['tahun'] == selected_year) & (filtered_data['jumlah'] >= threshold_value)]

    # Create a bar chart
    fig = px.bar(
        filtered,
        x='wilayah_bptd',
        y='jumlah',
        color='status_pemeriksaan',
        barmode='group',
        labels={'jumlah': 'Jumlah Kendaraan', 'wilayah_bptd': 'Wilayah BPTD'},
        title=f"Data Pemeriksaan Tahun {selected_year} (Jumlah ≥ {threshold_value})"
    )
    return fig

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

#pip install pandas dash plotly openpyxl